GET http://localhost:3001/api/persons/ HTTP/1.1
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "number": "1231-123-1123"
}


###
GET http://localhost:3001/info HTTP/1.1

###
GET http://localhost:3001/ HTTP/1.1

###

DELETE http://localhost:3001/api/persons/5 HTTP/1.1
